PHAsset 프레임워크 적용하기 #4
codesquad-member-2020/photos-5 pull request #11
Opened 2020-03-17 12:23 UTC by GangWoon

collectionView cell에 이미지를 추가하기 위해서 UICollectionViewCell을 상속받는 커스텀 클래스를 만들어서 imageView와 imageView의 이미지를 변경하는 메소드를 만들었습니다.
Photos 프레임워크를 사용해서 collecitonView cell에 이미지를 표시했습니다.
PHAsset을 생성할때 PHFetchOptions을 외부에서 받아오게 만들고 싶었지만, Photo를 다른 파일에서도 내포해야되서 한 클래스에서 처리하도록 결정했습니다.

2020-03-17 13:14 UTC, godrm commented
커밋 로그들을 보면 모두 기여하지 않은 것처럼 한 사람만 주로 보이는 이유는 무엇인가요?

2020-03-17 13:16 UTC, GangWoon commented
울라프의 컨디션이 안좋아서 혼자서 코딩을 했었습니다.
페어 프로그래밍을하기 위해서 더 노력하겠습니다.

2020-03-17 13:19 UTC, godrm requested changes
다음 피드백 내용을 확인해보고 resolve 한 다음에 머지하세요.

2020-03-17 13:19 UTC, godrm commented on PhotosApp/PhotosApp/Info.plist
> +	<string></string>
사용하는 문구를 꼭 명시하세요. 이게 사용자에게 그대로 보입니다.

2020-03-17 13:19 UTC, godrm commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
> +        fetchResult = PHAsset.fetchAssets(with: photoOptions)
이렇게 정렬해서 모두 fetch하는게 앱 실행하는 시점에서 사진이 많으면 오래 걸리지 않나요? 
바로 화면이 뜨는지 직접 (사진이 많은) 디바이스에서 실행해서 확인하세요.

2020-03-17 13:19 UTC, godrm commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
>              withReuseIdentifier: UICollectionViewCell.photosCellIdentifier,
Custom 셀 이름이 PhotoCell 인데 Identifier는 `UICollectionViewCell.photosCellIdentifier` 네요? PhotoCell과 관련이 있는게 아닐까요?

2020-03-17 13:19 UTC, godrm commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
> +            cell.apply(with: image)
여기 클로저는 동기 방식인가 비동기 방식인가요? 
셀이 재사용되는 데 이미지를 이렇게 적용해놓으면 스크롤 될때 문제되지는 않나요?

2020-03-17 13:19 UTC, godrm commented on PhotosApp/PhotosApp/View/Base.lproj/Main.storyboard
> +                                                    <rect key="frame" x="0.0" y="0.0" width="100" height="100"/>
이렇게 스토리보드에 이미지뷰 크기를 고정하면 Cell 크기를 늘리거나 작게 바꾸면 같이 줄어드나요?

2020-03-17 13:20 UTC, godrm commented
> 울라프의 컨디션이 안좋아서 혼자서 코딩을 했었습니다.
> 페어 프로그래밍을하기 위해서 더 노력하겠습니다.

그랬다면 구현 내용을 모를테니, 올라프에게도 리뷰를 받고 머지하세요.

2020-03-17 13:44 UTC, 1Consumption commented
더 이상 generateRandomColor를 사용하지 않는데 왜 아직 있을까요?

2020-03-17 13:45 UTC, GangWoon commented
놓친 부분이었습니다. 삭제하도록 하겠습니다.

2020-03-17 13:55 UTC, 1Consumption commented on PhotosApp/PhotosApp/View/Base.lproj/Main.storyboard
> +                                                    <rect key="frame" x="0.0" y="0.0" width="100" height="100"/>
넵 오토레이아웃 적용해서 가변적으로 잘 대응합니다

2020-03-17 13:57 UTC, GangWoon commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
>              withReuseIdentifier: UICollectionViewCell.photosCellIdentifier,
리뷰를 신청하기 전에 페어와 충분히 코드를 검토한 후에 리뷰를 신청하겠습니다.
너무 마음만 서둘러서 생긴 실수였습니다.

2020-03-18 08:18 UTC, 1Consumption commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
> +            cell.apply(with: image)
비동기 방식입니다.

requestImage(for:, targetSize:, contentMode:, options:, resultHandler:) 메소드에서 resultHandler가 최초 저화질의 이미지를 셀에 넣어주고, 화면에 보이는 모든 셀에 이미지가 들어간 후 다시 비동기적으로 고화질의 이미지를 넣어주는데, 지나치게 빠르게 스크롤할 경우 저화질의 이미지를 넣고 고화질의 이미지를 넣으려고 하는 순간, 셀이 바뀌면서 기대했던 이미지가 아닌, 이전 인덱스패스에 해당하는 고화질 이미지가 현재 셀에 들어가기 때문에 이상한 이미지가 들어갑니다.(저희들 생각입니다)
이를 보완하기 위해 현재 인덱스패스와 넣고자하는 이미지의 인덱스값과 같은지를 비교하고, 같으면 이미지를 넣어주도록 했습니다. 
그 결과 스크롤을 빠르게 해도 이미지가 꼬이지않고 잘 들어가는것을 확인했습니다.

2020-03-18 09:20 UTC, GangWoon commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
> +        fetchResult = PHAsset.fetchAssets(with: photoOptions)
아이폰 X에서 실행한 결과 사진이 약 1400장 정도 있었는데 바로 실행이 되는 모습을 확인했습니다.
그런데 엄청나게 많은 데이터가 있다면 느려질 수 있다고 생각했습니다.
그래서 저희가 생각한 방법은 PHFetchOptions.fetchLimit 속성을 변경하고 특정 이벤트(스크롤의 위치가 마지막인 경우와 더 받아올 데이터가 존재한 경우)가 발생하면  더 받아오도록 구현해야 될 거 같습니다. 하지만 구현은 못 했습니다. 어떻게 생각하시나요?

2020-03-18 09:27 UTC, godrm commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
> +        fetchResult = PHAsset.fetchAssets(with: photoOptions)
PHFetchOptions.fetchLimit 를 하고 prefetch 정도를 같이 하면 적당합니다. 
실제로 해보는게 어렵지 않으면 해보세요.

2020-03-18 09:33 UTC, godrm commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
> +        fetchResult = PHAsset.fetchAssets(with: photoOptions)
이런게 전형적으로 데이터가 많을 수록 느려지는 부분이니까 전체 데이터를 다 가져오는 건 항상 주의해야 합니다.

2020-03-18 09:33 UTC, godrm commented on PhotosApp/PhotosApp/Model/CollectionViewDataSource.swift
>              withReuseIdentifier: UICollectionViewCell.photosCellIdentifier,
실수를 통해 배우면 되죠. 스스로 인지할 수 있도록 코딩할 때 규칙을 정해보세요.

2020-03-18 09:34 UTC, godrm approved these changes
서로 확인했으면 머지하고 진행하시죠.

2020-03-18 11:49 UTC, GangWoon commented
PHFetchOptions.fetchLimit 와 prefetch를 사용해서 구현하고 넘어가세요

2020-03-19 11:27 UTC, merged